### ISSUE TITLE
ssh认证错误提示优化

### ISSUE THREAD

**Issue by Jonnyan404** [G3G4X5X6/ultimate-cube#18]
- 目前的错误提示有点奇怪,建议改为: 认证失败+未知的认证方法

另外:一些加密方法参考,从其它软件搬运
![image](https://user-images.githubusercontent.com/20352705/156497735-13c85918-a8ab-4575-93f8-fdd4cc9f5c22.png)

**Comment by G3G4X5X6** [comment]
1. 这个是贴近开发的提示，好定位问题，用户提示的话，可能需要创建自己的异常了信息了，后面看看怎么弄。
2. 加密方式的话，优先级比较低了，后面看看吧

**Comment by Jonnyan404** [comment]
> 1. 这个是贴近开发的提示，好定位问题，用户提示的话，可能需要创建自己的异常信息了，后面看看怎么弄。
> 2. 加密方式的话，优先级比较低了，后面看看吧

回复1: 我故意输错用户或者密码,但提示依然是: 没有更多认证方法可用 ~

**Comment by G3G4X5X6** [comment]
是这样子的，账户密码不对，会自动的不断尝试新的加密方式验证，直到都失败了，就提示 “没有更多认证方法可用” 了，其实就是用户名或密码不正确。这个提示信息的问题后面找时间统一一下。

**Comment by G3G4X5X6** [comment]
“支持多种加密方法” 加入TODO列表
